name: PHPStan

on: [workflow_dispatch, push, pull_request]

jobs:
  build-test:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        php:
          - 7.4
          - 8.0
          - 8.1
    name: 'PHPStan ${{ matrix.php }}'
    steps:
      - uses: actions/checkout@v2
      - uses: php-actions/composer@v6
      - uses: php-actions/phpstan@v3
        with:
          configuration: .phpstan.neon
          memory_limit: 256M
          php_version: "${{ matrix.php }}"
